### PR TITLE
sprint 2 completed

### PR DESCRIPTION
**Pull request by pawelstrzelczyk**

### CODE REVIEW

**Comment by codeblessing** [comment]
Ok, but you have to manually resolve conflicts.

**Review by jedrzej-smok — APPROVED** [review]

**Comment by pawelstrzelczyk** [comment]
> Ok, but you have to manually resolve conflicts.


but main is protected so how do i do that

**Comment by codeblessing** [comment]
> > Ok, but you have to manually resolve conflicts.
> 
> but main is protected so how do i do that

Ok, I disabled protection for main.

**Comment by pawelstrzelczyk** [comment]
done, please check if everything is ok
@codeblessing @Mmajonez

**Review by codeblessing — APPROVED** [review]

**Pull request merged**
